// console.log("Hello World");
// const Header = () => {
//   console.log("Hello World");
// };
// let favoriteColor = "Red";
// favoriteColor = "Blue";
// console.log(favoriteColor);
// let favoriteColor = "Red";
// console.log(favoriteColor);
// let colorFavorite = "Blue";
// console.log(colorFavorite);
// let userName: string = "Faizan";
// userName = "Faizan";
// let a: string = "Pakistan";
// let b: number = 9;
// let c: boolean = true;
//  let firstName: string = "Muhammad";
//  let lastName: string = "Faizan"
//  let fullName: string = firstName + " " + lastName;
//  console.log(fullName)
//  let middleName: string = "Ahmed";
//  console.log(middleName);
// let nameFirst: string = "Muhammad";
// let nameMiddle: string = "Faizan";
// let nameLast: string = "Ahmed";
// let nameFull: string = `${nameFirst} ${nameMiddle} ${nameLast}`;
// console.log(nameFull);
// let num1: number = 2;
// let num2: number = 5;
// let cart: number = num1 + num2;
// console.log(cart);
// let num1: number = 2;
// let num2: number = 5;
// let cart: number = num1 - num2;
// console.log(cart);
// let num1: number = 2;
// let num2: number = 5;
// let cart: number = num1 * num2;
// console.log(cart);
// let num1: number = 10;
// let num2: number = 2;
// let cart: number = num1 / num2;
// console.log(cart);
// let layer: number = 5;
// let apple: number = 5;
// let power: number = layer ** 2;
// console.log(power);
// console.log(5 % 2);
// let a = 5;
// let b = 4;
// console.log(a++);
// console.log(++b);
var a = 5;
var b = 2;
console.log(a--);
console.log(--b);
